version: '3.9'
services:
  rasa:
    build: .
    image: rasa/rasa:3.1.6-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  action-server-test:
    image: rasa/rasa-sdk:2.8.2
    volumes:
      - ./actions:/app/actions
    ports:
      - 5055:5055

  duckling:
    image: "rasa/duckling"
    ports:
      - 8000:8000